USE [Mega_DB]
GO

/****** Object:  Table [dbo].[ORDER_DETAILS]    Script Date: 05/04/2014 13:38:13 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ORDER_DETAILS]') AND type in (N'U'))
DROP TABLE [dbo].[ORDER_DETAILS]
GO

USE [Mega_DB]
GO

/****** Object:  Table [dbo].[ORDER_DETAILS]    Script Date: 05/04/2014 13:38:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ORDER_DETAILS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SKU] [varchar](50) NOT NULL,
	[UNIT_PRICE] [money] NOT NULL,
	[QTY] [int] NOT NULL,
	[TOTAL] [int] NOT NULL,
	[ORDER_ID] [int] NOT NULL,
 CONSTRAINT [PK_ORDER_DETAILS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


