USE [Mega_DB]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_SHIPPING_MASTER_COUNTRY]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SHIPPING_MASTER] DROP CONSTRAINT [DF_SHIPPING_MASTER_COUNTRY]
END

GO

USE [Mega_DB]
GO

/****** Object:  Table [dbo].[SHIPPING_MASTER]    Script Date: 05/01/2014 09:39:39 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SHIPPING_MASTER]') AND type in (N'U'))
DROP TABLE [dbo].[SHIPPING_MASTER]
GO

USE [Mega_DB]
GO

/****** Object:  Table [dbo].[SHIPPING_MASTER]    Script Date: 05/01/2014 09:39:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SHIPPING_MASTER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NULL,
	[SESSION_ID] [varchar](100) NOT NULL,
	[EMAIL] [varchar](100) NOT NULL,
	[NAME] [varchar](100) NOT NULL,
	[CITY] [varchar](100) NOT NULL,
	[STATE] [varchar](100) NOT NULL,
	[COUNTRY] [varchar](100) NOT NULL,
	[PIN] [int] NOT NULL,
	[ADDRESS] [varchar](100) NOT NULL,
	[MOBILE] [varchar](100) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SHIPPING_MASTER] ADD  CONSTRAINT [DF_SHIPPING_MASTER_COUNTRY]  DEFAULT ('India') FOR [COUNTRY]
GO


