USE [Mega_DB]
GO

/****** Object:  Table [dbo].[ORDER_STATUS]    Script Date: 05/04/2014 13:35:02 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ORDER_STATUS]') AND type in (N'U'))
DROP TABLE [dbo].[ORDER_STATUS]
GO

USE [Mega_DB]
GO

/****** Object:  Table [dbo].[ORDER_STATUS]    Script Date: 05/04/2014 13:35:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ORDER_STATUS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ORDER_ID] [int] NOT NULL,
	[STATUS] [varchar](50) NOT NULL,
	[LAST_MODIFIED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](50) NOT NULL,
	[DESCRIPTION] [varchar](max) NOT NULL,
 CONSTRAINT [PK_ORDER_STATUS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


