USE [Mega_DB]
GO

/****** Object:  Table [dbo].[ORDER_MASTER]    Script Date: 05/04/2014 13:36:39 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ORDER_MASTER]') AND type in (N'U'))
DROP TABLE [dbo].[ORDER_MASTER]
GO

USE [Mega_DB]
GO

/****** Object:  Table [dbo].[ORDER_MASTER]    Script Date: 05/04/2014 13:36:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ORDER_MASTER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ORDER_NO] [int] NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[PAYMINT_METHOD] [varchar](50) NOT NULL,
	[AMOUNT] [money] NOT NULL,
	[SHIPPING_CHARGE] [money] NOT NULL,
	[VAT] [money] NOT NULL,
	[TOTAL_AMOUNT] [money] NOT NULL,
	[SHIPPING_ID] [int] NOT NULL,
	[DOCKET_NO] [varchar](50) NOT NULL,
 CONSTRAINT [PK_ORDER_MASTER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


