
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_VISIT_RECENT_ITEMS_ProductNew_Master]') AND parent_object_id = OBJECT_ID(N'[dbo].[VISIT_RECENT_ITEMS]'))
ALTER TABLE [dbo].[VISIT_RECENT_ITEMS] DROP CONSTRAINT [FK_VISIT_RECENT_ITEMS_ProductNew_Master]
GO

IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_VISIT_RECENT_ITEMS_UserRegistration]') AND parent_object_id = OBJECT_ID(N'[dbo].[VISIT_RECENT_ITEMS]'))
ALTER TABLE [dbo].[VISIT_RECENT_ITEMS] DROP CONSTRAINT [FK_VISIT_RECENT_ITEMS_UserRegistration]
GO

USE [Mega_DB]
GO

/****** Object:  Table [dbo].[VISIT_RECENT_ITEMS]    Script Date: 04/17/2014 19:41:52 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VISIT_RECENT_ITEMS]') AND type in (N'U'))
DROP TABLE [dbo].[VISIT_RECENT_ITEMS]
GO

USE [Mega_DB]
GO

/****** Object:  Table [dbo].[VISIT_RECENT_ITEMS]    Script Date: 04/17/2014 19:41:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[VISIT_RECENT_ITEMS](
	[RECENT_ITEMS_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NULL,
	[IP] [varchar](150) NULL,
	[PRODUCT_ID] [int] NULL,
	[DATE] [datetime] NULL,
	[STATUS] [varchar](150) NULL,
 CONSTRAINT [PK_VISIT_RECENT_ITEMS] PRIMARY KEY CLUSTERED 
(
	[RECENT_ITEMS_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[VISIT_RECENT_ITEMS]  WITH CHECK ADD  CONSTRAINT [FK_VISIT_RECENT_ITEMS_ProductNew_Master] FOREIGN KEY([PRODUCT_ID])
REFERENCES [dbo].[ProductNew_Master] ([ProductNew_ID])
GO

ALTER TABLE [dbo].[VISIT_RECENT_ITEMS] CHECK CONSTRAINT [FK_VISIT_RECENT_ITEMS_ProductNew_Master]
GO

ALTER TABLE [dbo].[VISIT_RECENT_ITEMS]  WITH CHECK ADD  CONSTRAINT [FK_VISIT_RECENT_ITEMS_UserRegistration] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[UserRegistration] ([UserID])
GO

ALTER TABLE [dbo].[VISIT_RECENT_ITEMS] CHECK CONSTRAINT [FK_VISIT_RECENT_ITEMS_UserRegistration]
GO


